// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjoe_ivSDBXlNkS59Dab3bPmYoEipSk-E',
    appId: '1:717965335019:web:c5d776f4b43791fa5ae1ae',
    messagingSenderId: '717965335019',
    projectId: 'loopyfeed-1bb85',
    authDomain: 'loopyfeed-1bb85.firebaseapp.com',
    storageBucket: 'loopyfeed-1bb85.firebasestorage.app',
    measurementId: 'G-ZETNMBP2C9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeQvMemQGcDNkGrV63fhH9h8lWLHR0Byw',
    appId: '1:717965335019:android:7f9598fd22110bd95ae1ae',
    messagingSenderId: '717965335019',
    projectId: 'loopyfeed-1bb85',
    storageBucket: 'loopyfeed-1bb85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXdgQrx_jPLC79zUKrnQWoF6oeYhTQDxk',
    appId: '1:717965335019:ios:c0ad1eb7ed274a535ae1ae',
    messagingSenderId: '717965335019',
    projectId: 'loopyfeed-1bb85',
    storageBucket: 'loopyfeed-1bb85.firebasestorage.app',
    iosBundleId: 'com.zynth.loopyfeed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXdgQrx_jPLC79zUKrnQWoF6oeYhTQDxk',
    appId: '1:717965335019:ios:87599e984c75e8f55ae1ae',
    messagingSenderId: '717965335019',
    projectId: 'loopyfeed-1bb85',
    storageBucket: 'loopyfeed-1bb85.firebasestorage.app',
    iosBundleId: 'com.example.heroapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjoe_ivSDBXlNkS59Dab3bPmYoEipSk-E',
    appId: '1:717965335019:web:9c4c3565238b0ec35ae1ae',
    messagingSenderId: '717965335019',
    projectId: 'loopyfeed-1bb85',
    authDomain: 'loopyfeed-1bb85.firebaseapp.com',
    storageBucket: 'loopyfeed-1bb85.firebasestorage.app',
    measurementId: 'G-4Z1VMMEY9N',
  );
}
