///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String filesAbout = 'assets/files/about.md';
  static const String filesPrivacyPolicy = 'assets/files/privacy_policy.md';
  static const String filesTermsAndConditions = 'assets/files/terms_and_conditions.md';
  static const String iconsSettings = 'assets/icons/settings.svg';
  static const String iconsShare = 'assets/icons/share.svg';
  static const String profilePA = 'assets/profile/p_a.jpg';

  static const String profileTutorialScreen = 'assets/profile/tutorial_screen.png';
  static const String profileLikedVideosIllustration = 'assets/profile/liked_videos_illustration.png';
  static const String profileDarkIllustration = 'assets/profile/dark_illustration.png';
  static const String profileLightIllustration = 'assets/profile/light_illustration.png';
  static const String iconsBranding2 = 'assets/icons/branding_2.png';

  static const String iconsFacebook = 'assets/icons/facebook.svg';
  static const String iconsGoogle = 'assets/icons/google.svg';
  static const String iconsInstagram = 'assets/icons/instagram.svg';
  static const String iconsX = 'assets/icons/x.svg';
  static const String iconsPerson = 'assets/icons/person.svg';
  static const String iconsSettingsUser = 'assets/icons/settings_user.svg';

  static const String iconsPrimaryLogo = 'assets/icons/primary_logo.png';
  static const String iconsSecondaryLogo = 'assets/icons/secondary_logo.png';
  static const String iconsPrimaryLogoLight = 'assets/icons/app_icon_light.png';
  static const String iconsSecondaryLogoLight = 'assets/icons/branding_dark.png';
}
