///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String filesAbout = 'assets/files/about.md';
  static const String filesPrivacyPolicy = 'assets/files/privacy_policy.md';
  static const String filesTermsAndConditions = 'assets/files/terms_and_conditions.md';
  static const String iconsSettings = 'assets/icons/settings.svg';
  static const String iconsShare = 'assets/icons/share.svg';
  static const String profilePA = 'assets/profile/p_a.jpg';
}
